text_descriptions = [    
        'an arson',
        'a torching',
        'an incendiarism',
        'a firebombing',
        'a burning',
        'a fire',
        'a wildfire',
        'a blaze',
        'a conflagration',
        'an ignition',
        'a combustion',
        'a flashover',
        'a flame',

        'a smoky car',
        'a smoking car',
        'a burning car',
        'a burning gas station',
        'a gas station fire',
        'a burning person',
        'a burning running person',
        'a burning building',
        'a burning structure',
        'a burning garage',
        'a burning house',
        'a burning home',
        'a smoky room',
        'a smoke room',
        'a burning room',
        'a burning roof',
        'a burning furniture',
        'a burning door',
        'a burning wall',

        'a fire mixture',
        'an incendiary mixture',
        'incendiary bottles',
        'an incendiary bomb',
        'incendiaries',
        'a Molotov cocktail',
        'a smoke cloud',
        'a smoke',
        'a fume',
        'a haze',

        'an arsonist',
        'a person with fire',
        'a man throwing a fire mixture',
        'a man throwing an incendiary mixture',
        'a man throwing a Molotov cocktail',
        'a person setting a car on fire',
        'a person setting a house on fire',
        'a person burning down a house',
        'a person burning down a room',
        'a person burning down a furniture',
        'a flying Molotov cocktail',
        'people running from fire',
        

        'an assault',
        'an armed attack',
        'a shooting',
        'a shootout',
        'a gunfight',
        'an act of terrorism',

        'terrorist',
        'attacker',
        'a gunman',
        'an armed man',
        'a man with a gun',
        'men with guns',
        'a man with a machine gun',
        'men with machine guns',
        'a killer',
        'a shooting man',
        'a shot',

        'a fight',
        'a fighting',
        'a brawl',
        'a battle',
        'a scuffle',
        'a knifing',

        'a man with a knife',
        'men with knives',
        'a kicking man',
        'a man lying on the ground',
        'a man lying in the street',
        'people running',


        'an explosion',
        'a detonation',
        'a blast',

        'a cloud of dust',
        'a dust cloud',
        'an exploded car',
        'an exploded building',
        'a debris',
        'a debris lying on the ground',
        'an overturned car',
        'an overturned furniture',


        'a road accident',
        'a traffic accident',
        'a car accident',
        'a car collision',
        'a crashed car',
        'a broken car',

        'a car crashing into people',
        'a car crashing into the wall',
        'a car crashing into the fence',
        'a car crashing into bike',
        'a bike crashing into people',
        'a bike crashing into the wall',
        'a bike crashing into the fence',
        'a bus crashing into car',
        'a bus crashing into bike',
        'a bus crashing into people',
        'a bus crashing into the wall',
        'a bus crashing into the fence',
        'a truck crashing into car',
        'a truck crashing into bike',
        'a truck crashing into people',
        'a truck crashing into the wall',
        'a truck crashing into the fence',


        'a vandalism',

        'a man drawing on the wall',
        'a man drawing on the car',
        'a man breaking down a car',
        'a man breaking a furniture',
        'a man throwing stones',


        'a pizza, a type of food',
        ]
